#517189 [C#テキスト]17章演習問題
sugisaka-being/sugisaka_textC pull request #17
Opened 2024-12-05 07:44 UTC by sugisaka-being

17章演習問題の解答を作成いたしました。

17章の概要[実践オブジェクト指向プログラミング]
・ポリモーフィズムの基礎
・Template Methodパターン
・Strategyパターン

2024-12-12 07:50 UTC, haraguchi-being reviewed
解答の作成ありがとうございます。
いくつかコメントしたため、確認をお願いします。

2024-12-12 07:50 UTC, haraguchi-being commented on Chapter17/Chapter17-1-1/ToHankakuNumberProcesser.cs
> +            vTextLine = new string(vTextLine.Select(x => '０' <= x && x <= '９' ? (char)(x - '０' + '0') : x).ToArray());
newをしているため、動作的には問題ないかと思いますが、string型の引数をそのまま使っている状態のため、`var`で新しく宣言してもらったほうが良いかと思います。
予期しない影響があったりするため。

2024-12-12 07:50 UTC, haraguchi-being commented on Chapter17/Chapter17-1-1/Program17-1-1.cs
> +        }
いつものチェック処理ですね。Goodです。

2024-12-12 07:50 UTC, haraguchi-being commented on Chapter17/Chapter17-1-1/Program17-1-1.cs
> +            if (!ExistsFileWithExtension(wInputFilePath, ".txt")) return;
ガード節が使用できていてGoodです。

2024-12-12 07:50 UTC, haraguchi-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
.csのファイルが多数あって平置きの状態なので、フォルダー分けしてもよいかと思います。
Converter用のフォルダを作って、そこにConverterの.csファイルを格納しておくなど。
そうすると、本体のプログラムがどれかわかりやくなります。

2024-12-12 07:50 UTC, haraguchi-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +                ConverterBase wToConvert = GetConverter("変換先の単位を入力してください");
ここは、何を入力すればいいかわからないため、単位の入力例があるとよいです。
あと、間違った値が入力されたときに何かメッセージが表示されると親切かと思います。

2024-12-12 07:50 UTC, haraguchi-being commented on Chapter17/Chapter17-1-3/Program17-1-3.cs
> +        }
Goodです。

2024-12-12 07:50 UTC, haraguchi-being commented on Chapter17/Chapter17-1-3/ToHankakuService.cs
> +            vTextLine = new string(vTextLine.Select(x => '０' <= x && x <= '９' ? (char)(x - '０' + '0') : x).ToArray());
問題17-1-1と同様です。

2024-12-13 01:06 UTC, sugisaka-being commented on Chapter17/Chapter17-1-1/ToHankakuNumberProcesser.cs
> +            vTextLine = new string(vTextLine.Select(x => '０' <= x && x <= '９' ? (char)(x - '０' + '0') : x).ToArray());
コメントありがとうございます。
引数をそのまま使うのではなく、新しく変数を宣言いたしました。
```
protected override void Execute(string vTextLine) {
    var wConvertedTextLine = new string(vTextLine.Select(x => '０' <= x && x <= '９' ? (char)(x - '０' + '0') : x).ToArray());
    Console.WriteLine(wConvertedTextLine);
}
```

2024-12-13 01:07 UTC, sugisaka-being commented on Chapter17/Chapter17-1-3/ToHankakuService.cs
> +            vTextLine = new string(vTextLine.Select(x => '０' <= x && x <= '９' ? (char)(x - '０' + '0') : x).ToArray());
17-1-1と同様に、新しく変数を宣言いたしました。
```
public void Execute(string vTextLine) {
    var wConvertedTextLine = new string(vTextLine.Select(x => '０' <= x && x <= '９' ? (char)(x - '０' + '0') : x).ToArray());
    Console.WriteLine(wConvertedTextLine);
}
```

2024-12-13 01:31 UTC, sugisaka-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +                ConverterBase wToConvert = GetConverter("変換先の単位を入力してください");
コメントありがとうございます。
ユーザーが入力を迷ってしまわないように、入力例やメッセージが表示されるコードを追加いたしました。
```
ConverterBase wFromConvert = GetConverter("変換元の単位を入力してください　例）キロメートル");
ConverterBase wToConvert = GetConverter("変換先の単位を入力してください　例）マイル");
```
```
static ConverterBase GetConverter(string vOutputMessage) {
    ....
    if (wConverter == null) Console.WriteLine($"入力された単位は無効です。例を参考に再度入力し直してください");
    ...
}
```

2024-12-13 01:42 UTC, sugisaka-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
ありがとうございます。
`Converters`というクラスを作成し、そこに`Converter`の`.cs`ファイルを格納いたしました。

2024-12-13 11:05 UTC, r-nishiguchi-being requested changes

2024-12-13 11:05 UTC, r-nishiguchi-being commented on Chapter17/Chapter17-1-2/ConverterBase.cs
> +        protected abstract double FRatio { get; }
プロパティなので、Fは付けなくてよいですね。

2024-12-13 11:05 UTC, r-nishiguchi-being commented on Chapter17/Chapter17-1-2/KiloMeterConverter.cs
> +        protected override double FRatio { get { return 1000; } }
こんな感じで書けませんかね？
```
protected override double Ratio => 1000;
```

2024-12-13 11:05 UTC, r-nishiguchi-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +        static double GetDistance(ConverterBase vFromConvert) {
メソッド名はユーザー入力を受けているのでGetよりReadの方がより適していますね。
何か書籍で指定されていたらすみません。

2024-12-14 00:32 UTC, teshima-being reviewed
読みやすかったです。
細かい点が多いですが、いくつかコメントしてますので確認お願いします。

2024-12-14 00:32 UTC, teshima-being commented on Chapter17/Chapter17-1-1/Program17-1-1.cs
> +            var wInputFilePath = Console.ReadLine();
現在のパスの入力例ではコンソールに`例)"C:\Users\Documents\Sample17-1-1.txt"`と表示されますが、例に則って`""`でパスを囲うとファイルが見つからずエラーとなります。特に理由がなければ例から`""`は無くしてしまった方が良いです。
実際にプログラムを使う人から見たときに、どうすればよりスムーズに利用できるようになるかという視点も大切ですね。

※Program17-1-3.csについても同様です。

2024-12-14 00:32 UTC, teshima-being commented on Chapter17/Chapter17-1-1/TextProcessor.cs
> +        protected virtual void Initialize(string vFilePath) { }
`Execute()`メソッドや`Terminate()`メソッドは`ToHankakuNumberProcesser`クラス（ちなみに`Processer → Processor`ですね）でオーバーライドされていますが、`Initialize()`メソッドは現在オーバーライドされておらず、処理を行わない空のメソッドになっています。この状態であれば、メソッド自体を削除するか、初期化を派生クラスで定義する設計に変更した方が良いでしょう。どちらを選ぶかは、このクラスの将来的な拡張性や設計意図によります。

2024-12-14 00:32 UTC, teshima-being commented on Chapter17/Chapter17-1-2/ConverterBase.cs
> +        }
ラムダ式を用いて簡潔に書けます。
他にも同様に簡略化できる箇所がないか確認してみてください。

2024-12-14 00:32 UTC, teshima-being commented on Chapter17/Chapter17-1-2/KiloMeterConverter.cs
> +        /// <returns>キロメートルの単位であればtureを返す</returns>
`ture → true`ですね。
おそらくコピペの影響と推察しますが、MileConverter.csについても同様になっています。

コメント部分なのでコードの動作には一切影響しませんが、影響がないゆえにこのような誤字は一度製品のコードに含まれて世に出るとその後ずっと修正されず残ってしまうこともあります。
だからこそ、新たに実装するときは細かい誤字脱字も含めて確認できると良いですね。

2024-12-14 00:32 UTC, teshima-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +            } while (wDistanceValue == null);
`wDistanceValue`と`wValue`の二つの変数を定義していますが、どちらか一方だけでやりたいことは実現できないでしょうか。

また`wDistanceValue`をnull許容型にしている特別な理由はありますか？
27行目で、`TryParse()`がfalseなら`wDistanceValue`にnullを代入し、`wDistanceValue`がnullの間はループするようになっていますが、「ユーザーの入力値が数値に変換できない場合はループをする」だけであれば、わざわざnull許容型にしなくても良さそうに思えたため聞いてみた次第です。

変数が取りうる状態を増やすということは、それだけその変数を取り扱うときに注意すべき点が増えるということになります。理由があれば問題ないですが、特に理由がないのであれば極力避けたほうが良いように思います。

2024-12-14 00:32 UTC, teshima-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +        /// <param name="vFromConvert"変換元の単位コンバーター></param>
`>`の位置がずれています。
今の状態だとパラメータの説明文として認識してもらえていないので、下記のように修正しましょう。
`<param name="vFromConvert"変換元の単位コンバーター></param>`
↓
`<param name="vFromConvert">変換元の単位コンバーター</param>`

2024-12-14 00:32 UTC, teshima-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +            } while (wConverter == null);
※追加課題
先日「リーダブルコード」を読んでいる最中かと思いますが、リーダブルコードに「do - whileループではなくwhileループを使いましょう」というような記述があったような気がします。
せっかくであれば、他にdo - whileループを使用している箇所も含めて、whileループに書き換えられないか検討してみてください。

コードは通常上から下に読んでいくので、do - whileループを使うとコードを2回読むことになってしまいます。
（上から読み進めたあとに条件が出てくるので、もう一度条件を確認したうえで読み直すことになる。）

2024-12-14 00:32 UTC, teshima-being commented on Chapter17/Chapter17-1-3/TextFileProcessor.cs
> +        }
※参考
[コーディング規約](https://dev-redmine.being.group/projects/sirius-client/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84#:~:text=%E3%83%95%E3%82%A3%E3%83%BC%E3%83%AB%E3%83%89%EF%BC%9A%E6%8E%A5%E9%A0%AD%E8%BE%9E%E3%81%AE%20%22F%22%20%E3%81%A7%E8%87%AA%E8%BA%AB%E3%81%AE%E3%83%95%E3%82%A3%E3%83%BC%E3%83%AB%E3%83%89%E3%81%A0%E3%81%A8%E5%88%86%E3%81%8B%E3%82%8B%E3%81%AE%E3%81%A7%20this%20%E3%82%92%E4%BB%98%E3%81%91%E3%81%AA%E3%81%8F%E3%81%A6%E3%82%82%E3%81%84%E3%81%84%E3%80%82%E4%BB%98%E3%81%91%E3%81%A6%E3%82%82%E3%81%84%E3%81%84%E3%80%82)にあるように、フィールドには`this`を付けなくても良いです。
（接頭辞のFで自身のフィールドだと分かるため）
付けてもよいですが、30行目や33行目では付いておらず、少し統一感に欠けるのでどちらかに揃えるのが良い気がします。

2024-12-14 00:32 UTC, teshima-being commented on Chapter17/Chapter17-1-3/ToHankakuService.cs
> +        /// <param name="vFileFath"></param>
引数についての説明の追加をお願いします。
自明で不要そうだとの判断ならタグごと削除しておきましょう。

2024-12-17 00:25 UTC, sugisaka-being commented on Chapter17/Chapter17-1-2/ConverterBase.cs
> +        protected abstract double FRatio { get; }
コメントありがとうございます。
プロパティの`F`を削除いたしました・

2024-12-17 00:35 UTC, sugisaka-being commented on Chapter17/Chapter17-1-2/KiloMeterConverter.cs
> +        protected override double FRatio { get { return 1000; } }
コメントありがとうございます。
教えていただいたように、プロパティにラムダ式を利用いたしました。

2024-12-17 00:38 UTC, sugisaka-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +        static double GetDistance(ConverterBase vFromConvert) {
コメントありがとうございます。
Readの方が適しているとのこと非常に勉強になります。
課題図書でも変数名のつけ方について学んでいる最中であるため、「名前に情報を詰め込む」ということをより意識してコードを書いていきます。

2024-12-17 00:43 UTC, sugisaka-being commented on Chapter17/Chapter17-1-1/Program17-1-1.cs
> +            var wInputFilePath = Console.ReadLine();
コメントありがとうございます。
確かに現在のままの入力例だとユーザーがパスを`""`で囲まなければならないと間違えて認識してしまうと感じました。
今後は、ユーザーに誤解を与えてしまわないような書き方を意識します。

以下のようにコードを修正をいたしました。
`Console.WriteLine("読み込むファイルの絶対パスを入力してください。例）C:\\Users\\Documents\\Sample17-1-1.txt");`

2024-12-17 00:50 UTC, sugisaka-being commented on Chapter17/Chapter17-1-1/TextProcessor.cs
> +        protected virtual void Initialize(string vFilePath) { }
コメントありがとうございます。
誤字に関して、`ToHankakuNumberProcesser`を`ToHankakuNumberProcessor`に修正いたしました。
また、将来の拡張性を考慮し、`Initialize()`メソッドを派生クラスで定義いたしました。

2024-12-17 00:59 UTC, sugisaka-being commented on Chapter17/Chapter17-1-2/ConverterBase.cs
> +        }
コメントありがとうございます。
ラムダ式を用いて簡略化できる部分に関して、コードを簡略化いたしました。

2024-12-17 01:15 UTC, sugisaka-being commented on Chapter17/Chapter17-1-2/KiloMeterConverter.cs
> +        /// <returns>キロメートルの単位であればtureを返す</returns>
誤字を修正いたしました。`ture`→`true`
ありがとうございます。動作に直接影響がない動作に関しても、誤りがないかしっかりと確認を行いたいと思います。

2024-12-17 01:41 UTC, sugisaka-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +            } while (wDistanceValue == null);
コメントありがとうございます。
`wDistanceValue`と`wValue`と定数を2つ用意しなくても、やりたい動作を実現できることができました。

また、null許容型に関して、特別な理由がないにもかかわらず「`TryParse()`が`false`の際に、`null`を代入してループを回せばよいのか」とテキストの考え方の通りにコードを記述していました。そのため、変数がとりうる状態が増えているということまで考慮できていませんでした。
今後は、「ほかの方法で実現ができないか」をもっと考えられるようになりたいです。
そして、数値の変換に失敗した場合にループをするようコードを修正いたしました。
```
static double GetDistance(ConverterBase vFromConvert) {
    double wDistanceValue;
    do {
        Console.Write($"変換したい距離(単位:{vFromConvert.UnitName})を入力してください　例)100 => ");
        if (!double.TryParse(Console.ReadLine(), out wDistanceValue)) {
            Console.WriteLine($"入力された距離は無効です。例を参考に再度入力し直してください");
            continue;
        }
        break;
    } while (true);
    return wDistanceValue;
}
```

2024-12-17 01:43 UTC, sugisaka-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +        /// <param name="vFromConvert"変換元の単位コンバーター></param>
ご指摘ありがとうございます。
パラメータ部分のコメントを以下のように修正いたしました。
`/// <param name="vFromConvert">変換元の単位コンバーター</param>`

2024-12-17 02:19 UTC, sugisaka-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +            } while (wConverter == null);
コメントありがとうございます。
`do-while`ループを利用している箇所について、`while`ループを利用するようコードを修正いたしました。
ご指摘いただいた箇所に関しては、修正後以下のようなコードになりました。
```
static ConverterBase GetConverter(string vOutputMessage) {
    ConverterBase wConverter = null;
    Console.Write(vOutputMessage + " => ");
    while ((wConverter = ConverterFactory.GetInstance(Console.ReadLine())) == null) {
        Console.WriteLine($"入力された単位は無効です。例を参考に再度入力し直してください");
        Console.Write(vOutputMessage + " => ");
    }
    return wConverter;
}
```

2024-12-17 02:25 UTC, sugisaka-being commented on Chapter17/Chapter17-1-3/TextFileProcessor.cs
> +        }
ご指摘ありがとうございます。
リーダブルコードでもコードの一貫性の大切さが記述されていたため、今後は一貫性もしっかり意識できるようになりたいです。

2024-12-17 02:42 UTC, sugisaka-being commented on Chapter17/Chapter17-1-3/ToHankakuService.cs
> +        /// <param name="vFileFath"></param>
引数の説明に関して、自明だと感じたためタグを削除いたしました。

2024-12-17 04:44 UTC, r-nishiguchi-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +        static double GetDistance(ConverterBase vFromConvert) {
メソッド名とかで悩むときは.Netのメソッド名を参考にしてみるといいかもです。
プロパティに値を設定する系はSetとか、文字列を読み込んだり書き込んだり系はRead/Writeがよく使われるため、
自分が実装するときもそのルールに則ったりします。

https://learn.microsoft.com/ja-jp/dotnet/api/system.console?view=net-8.0

2024-12-17 04:54 UTC, teshima-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +            } while (wDistanceValue == null);
いいですね。このコードに加えて`do while`文を解消すればより良くなると思います。
上記コードをもう少し簡潔に書き換えるとすると下記のような感じですかね？
```
static double GetDistance(ConverterBase vFromConvert) {
    while (true) {
        Console.Write($"変換したい距離(単位:{vFromConvert.UnitName})を入力してください　例)100 => ");
        if (double.TryParse(Console.ReadLine(), out double wDistanceValue)) return wDistanceValue;
        Console.WriteLine("入力された値は無効です。数値を入力してください");
    }
}
```

もし、入力例のメッセージは最初の一回だけ表示すればよいのであれば、下記のような書き方もありかもしれません。
```
static double GetDistance(ConverterBase vFromConvert) {
    double wDistanceValue;
    Console.Write($"変換したい距離(単位:{vFromConvert.UnitName})を入力してください　例)100{Environment.NewLine}=> ");
    while (!double.TryParse(Console.ReadLine(), out wDistanceValue)) {
        Console.Write($"入力された距離は無効です。例を参考に再度入力し直してください{Environment.NewLine}=> ");
    }
    return wDistanceValue;
}
```

2024-12-17 04:56 UTC, teshima-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +            } while (wConverter == null);
`GetDistance()`メソッドについてもwhile文で書き換えてくれたみたいですね！
そちらについてはもう少し簡潔に記述できそうだったので、[コメント](https://github.com/sugisaka-being/sugisaka_textC/pull/17#discussion_r1887894615)を参考にもう少し改良してみてください。

2024-12-17 05:01 UTC, teshima-being commented on Chapter17/Chapter17-1-2/ConverterBase.cs
> +        }
前回の見落としですみませんが、`ToMeter()`メソッドの引数名が`vFeet`になっていますが、ここの単位はフィートとは限らないと思いますので、`DistanceConverter.cs`の`Convert()`メソッドのように`vDistanceValue`とかの方が良いかもしれません。

2024-12-17 06:19 UTC, sugisaka-being commented on Chapter17/Chapter17-1-2/ConverterBase.cs
> +        }
コメントありがとうございます。
`ToMeter()`メソッドで利用する引数名を`vDistanceValue`へ修正いたしました。

2024-12-17 06:35 UTC, sugisaka-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +            } while (wDistanceValue == null);
コメントありがとうございます。
`GetDistance()`メソッドについて、以下のようにコードを修正いたしました。
```
static double GetDistance(ConverterBase vFromConvert) {
    while (true) {
        Console.Write($"変換したい距離(単位:{vFromConvert.UnitName})を入力してください　例)100 => ");
        if (double.TryParse(Console.ReadLine(), out double wDistanceValue)) return wDistanceValue;
        Console.WriteLine($"入力された距離は無効です。例を参考に再度入力し直してください");
    }
}
```

また、いただいたコメントを参考にGetConverter()メソッドにも修正を加えました。
```
static ConverterBase GetConverter(string vOutputMessage) {
    while (true) {
        ConverterBase wConverter;
        Console.Write(vOutputMessage + " => ");
        if ((wConverter = ConverterFactory.GetInstance(Console.ReadLine())) != null) return wConverter;
        Console.WriteLine($"入力された単位は無効です。例を参考に再度入力し直してください");
    }
}
```

2024-12-18 01:35 UTC, haraguchi-being commented on Chapter17/Chapter17-1-1/ToHankakuNumberProcesser.cs
> +            vTextLine = new string(vTextLine.Select(x => '０' <= x && x <= '９' ? (char)(x - '０' + '0') : x).ToArray());
OKです。修正ありがとうございます。

2024-12-18 01:36 UTC, haraguchi-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
OKです。修正ありがとうございます。

2024-12-18 01:38 UTC, haraguchi-being commented on Chapter17/Chapter17-1-2/Program17-1-2.cs
> +                ConverterBase wToConvert = GetConverter("変換先の単位を入力してください");
OKです。修正ありがとうございます。

2024-12-18 01:40 UTC, haraguchi-being commented on Chapter17/Chapter17-1-3/ToHankakuService.cs
> +            vTextLine = new string(vTextLine.Select(x => '０' <= x && x <= '９' ? (char)(x - '０' + '0') : x).ToArray());
OKです。修正ありがとうございます。

2024-12-18 04:31 UTC, merged